name: Cloudways API Execute Via Git Action

on:
  push:
    branches:
      - 'main'
            
  pull_request:
    branches:
      - 'main'
      - 'stage'
    types:
      - closed

jobs:
  cloudways-deployment:
    name: Cloudways Deployment

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cloudways API Git Action
        uses: RafinBiswas/cloudways-api-action@stable
        with:
          email: ${{ secrets.CLOUDWAYS_EMAIL }}
          api-key: ${{ secrets.CLOUDWAYS_API_KEY }}
          api-version: "v1"
          api-path: "/git/pull"
          request-method: "POST"
          request-body: |
            server_id:${{ secrets.CLOUDWAYS_SERVER_ID }}
            git_url:${{ secrets.CLOUDWAYS_GIT_URL }}
            branch:main
          token-required: "false"
          request-response: |
            data.status:success
          prefix: "cw_"

      - name: Verify Deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
