name: Cloudways API Execute Via Git Action

on:
  push:
    branches:
      - 'main'
            
jobs:
  cloudways-deployment:
    name: Cloudways Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Cloudways via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CLOUDWAYS_HOST }}
          username: ${{ secrets.CLOUDWAYS_USERNAME }}
          key: ${{ secrets.CLOUDWAYS_SSH_KEY }}
          script: |
            cd ${{ secrets.CLOUDWAYS_DEPLOY_PATH }}
            git pull origin main
            echo "Deployment completed successfully!"

      - name: Verify Deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
